<a href="https://colab.research.google.com/github/Infant-Joshva/Data-Science-learning-path/blob/main/Project_4(Multiple_Disease_Prediction)/notebooks/Liver_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset-1 (Liver Disease Prediction) - Data Preprocessing

#### Importing Necessary Packages for Data Preprocessing

In [117]:
import pandas as pd

In [118]:
sheet_id= '1uiQfhlb0isYp2JefSVzIJOngN0viwsP0PzcMab-dUw8'
sheet_name = "sheet1"

#https://docs.google.com/spreadsheets/d/1uiQfhlb0isYp2JefSVzIJOngN0viwsP0PzcMab-dUw8/edit?gid=13099343#gid=13099343

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

liver_df=pd.read_csv(url)

### Exporting RAW dataset

In [119]:
liver_df.to_csv('liver_disease_raw.csv')

In [120]:
liver_df

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[583 rows x 11 columns]

####Data Type conversion

In [121]:
liver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         583 non-null    int64  
 1   Gender                      583 non-null    object 
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64  
 5   Alamine_Aminotransferase    583 non-null    int64  
 6   Aspartate_Aminotransferase  583 non-null    int64  
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  579 non-null    float64
 10  Dataset                     583 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB


In [122]:
# All datatypes are correct no need to replace

####Handling Null Values

In [123]:
liver_df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [124]:
(4/586)*100

0.6825938566552902

In [125]:
liver_df.dropna(inplace=True)

In [126]:
liver_df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [127]:
liver_df['Albumin_and_Globulin_Ratio'].unique()

array([0.9 , 0.74, 0.89, 1.  , 0.4 , 1.3 , 1.1 , 1.2 , 0.8 , 0.6 , 0.87,
       0.7 , 0.92, 0.55, 0.5 , 1.85, 0.95, 1.4 , 1.18, 0.61, 1.34, 1.39,
       1.6 , 1.58, 1.25, 0.78, 0.76, 1.55, 0.71, 0.62, 0.67, 0.75, 1.16,
       1.5 , 1.66, 0.96, 1.38, 0.52, 0.47, 0.93, 0.48, 0.58, 0.69, 1.27,
       1.12, 1.06, 0.53, 1.03, 0.68, 1.9 , 1.7 , 1.8 , 0.3 , 0.97, 0.35,
       1.51, 0.64, 0.45, 1.36, 0.88, 1.09, 1.11, 1.72, 2.8 , 0.46, 0.39,
       1.02, 2.5 , 0.37])

In [128]:
# Handeled all null values

In [129]:
liver_df['Age'].unique()

array([65, 62, 58, 72, 46, 26, 29, 17, 55, 57, 64, 74, 61, 25, 38, 33, 40,
       51, 63, 34, 20, 84, 52, 30, 48, 47, 45, 42, 50, 85, 35, 21, 32, 31,
       54, 37, 66, 60, 19, 75, 68, 70, 49, 14, 13, 18, 39, 27, 36, 24, 28,
       53, 15, 56, 44, 41,  7, 22,  8,  6,  4, 43, 23, 12, 69, 16, 78, 11,
       73, 67, 10, 90])

In [130]:
liver_df['Gender'].value_counts()

Gender
Male      439
Female    140
Name: count, dtype: int64

In [131]:
liver_df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Dataset'],
      dtype='object')

####Deleting Duplicate Values

In [132]:
liver_df.duplicated().sum()

np.int64(13)

In [133]:
liver_df.drop_duplicates(inplace=True)

In [134]:
liver_df.duplicated().sum()

np.int64(0)

In [135]:
liver_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 566 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         566 non-null    int64  
 1   Gender                      566 non-null    object 
 2   Total_Bilirubin             566 non-null    float64
 3   Direct_Bilirubin            566 non-null    float64
 4   Alkaline_Phosphotase        566 non-null    int64  
 5   Alamine_Aminotransferase    566 non-null    int64  
 6   Aspartate_Aminotransferase  566 non-null    int64  
 7   Total_Protiens              566 non-null    float64
 8   Albumin                     566 non-null    float64
 9   Albumin_and_Globulin_Ratio  566 non-null    float64
 10  Dataset                     566 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 53.1+ KB


In [136]:
liver_df

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset  
0        3.3                        0.90        1  
1        3.2                        0.74        1  
2        3.3                        0.89        1  
3        3.4                        1.00        1  
4        2.4                        0.40        1  
..       ...                         ...      ...  
578      1.6                        0.37        2  
579      3.2                        1.10        1  
580      3.2                        1.00        1  
581      3.4                        1.00        1  
582      4.4                        1.50        2  

[566 rows x 11 columns]

### EDA Process - For Features Selection

**The major types of analysis you’ll typically do in data preprocessing for ML, it’s mainly:**



---


1. Univariate Analysis
* One variable at a time.

* Purpose: Understand distribution, central tendency, spread, and outliers.


---


2. Bivariate Analysis
* Two variables at a time.

* Purpose: Find relationships, correlations, and trends.


---


3. Multivariate Analysis
* Three or more variables together.

* Purpose: Detect combined effects, interactions, patterns, and multicollinearity.


---


4. Missing Value Analysis
* Purpose: Identify and handle missing or incomplete data.


---


5. Outlier Analysis
* Purpose: Detect and decide how to treat extreme/unusual values.


---


6. Correlation Analysis
* Purpose: Measure relationship strength, avoid redundant features.


---


7. Class Imbalance Analysis (for classification problems)
* Purpose: Check if target variable has uneven distribution.

#### Importing Necessary Packages for EDA

In [137]:
# For plots
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
# For Stats
import numpy as np
import scipy.stats as stats
from scipy.stats import ttest_ind

#### Univarient Analysis

In [138]:
liver_df.describe()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
count  566.000000       566.000000        566.000000            566.000000   
mean    44.886926         3.338869          1.505830            292.567138   
std     16.274893         6.286728          2.841485            245.936559   
min      4.000000         0.400000          0.100000             63.000000   
25%     33.000000         0.800000          0.200000            176.000000   
50%     45.000000         1.000000          0.300000            208.000000   
75%     58.000000         2.600000          1.300000            298.000000   
max     90.000000        75.000000         19.700000           2110.000000   

       Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
count                566.000000                  566.000000      566.000000   
mean                  80.143110                  109.892226        6.494876   
std                  182.044881                  291.841897        1.087512   
min                   10.000000                   10.000000        2.700000   
25%                   23.000000                   25.000000        5.800000   
50%                   35.000000                   41.000000        6.600000   
75%                   60.750000                   87.000000        7.200000   
max                 2000.000000                 4929.000000        9.600000   

          Albumin  Albumin_and_Globulin_Ratio     Dataset  
count  566.000000                  566.000000  566.000000  
mean     3.145583                    0.948004    1.286219  
std      0.795745                    0.319635    0.452393  
min      0.900000                    0.300000    1.000000  
25%      2.600000                    0.700000    1.000000  
50%      3.100000                    0.950000    1.000000  
75%      3.800000                    1.100000    2.000000  
max      5.500000                    2.800000    2.000000

In [139]:
liver_df['Dataset'].unique()

array([1, 2])

In [140]:
liver_df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Dataset'],
      dtype='object')

In [141]:
#Finding outlier for each column

for col in liver_df.columns:
  fig1 = px.box(liver_df, x=col, title=f'{col} Box plot')
  fig1.show()
  print('-'*200)
  fig2 = px.histogram(liver_df, x=col, title=f'{col} Distribution')
  fig2.show()
  print('-'*200)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#### Bivarient Analysis

* Our target is Dataset, so X will be Attrition for all.

In [142]:
# sns.pairplot(liver_df, hue='Dataset')

In [143]:
selected_df = liver_df.select_dtypes(include=['int64', 'float64'])
corr_df = selected_df.corr()
corr_df

Age  Total_Bilirubin  Direct_Bilirubin  \
Age                         1.000000         0.010704          0.006268   
Total_Bilirubin             0.010704         1.000000          0.873975   
Direct_Bilirubin            0.006268         0.873975          1.000000   
Alkaline_Phosphotase        0.080085         0.205286          0.233653   
Alamine_Aminotransferase   -0.084319         0.216776          0.236731   
Aspartate_Aminotransferase -0.017352         0.238167          0.257965   
Total_Protiens             -0.195893        -0.008423         -0.000735   
Albumin                    -0.269448        -0.223979         -0.230650   
Albumin_and_Globulin_Ratio -0.215967        -0.207740         -0.201519   
Dataset                    -0.133821        -0.224467         -0.250926   

                            Alkaline_Phosphotase  Alamine_Aminotransferase  \
Age                                     0.080085                 -0.084319   
Total_Bilirubin                         0.205286                  0.216776   
Direct_Bilirubin                        0.233653                  0.236731   
Alkaline_Phosphotase                    1.000000                  0.125917   
Alamine_Aminotransferase                0.125917                  1.000000   
Aspartate_Aminotransferase              0.166609                  0.791754   
Total_Protiens                         -0.028623                 -0.035104   
Albumin                                -0.166287                 -0.026890   
Albumin_and_Globulin_Ratio             -0.236251                 -0.006525   
Dataset                                -0.186057                 -0.161617   

                            Aspartate_Aminotransferase  Total_Protiens  \
Age                                          -0.017352       -0.195893   
Total_Bilirubin                               0.238167       -0.008423   
Direct_Bilirubin                              0.257965       -0.000735   
Alkaline_Phosphotase                          0.166609       -0.028623   
Alamine_Aminotransferase                      0.791754       -0.035104   
Aspartate_Aminotransferase                    1.000000       -0.022114   
Total_Protiens                               -0.022114        1.000000   
Albumin                                      -0.084821        0.783800   
Albumin_and_Globulin_Ratio                   -0.072899        0.234576   
Dataset                                      -0.151009        0.036443   

                             Albumin  Albumin_and_Globulin_Ratio   Dataset  
Age                        -0.269448                   -0.215967 -0.133821  
Total_Bilirubin            -0.223979                   -0.207740 -0.224467  
Direct_Bilirubin           -0.230650                   -0.201519 -0.250926  
Alkaline_Phosphotase       -0.166287                   -0.236251 -0.186057  
Alamine_Aminotransferase   -0.026890                   -0.006525 -0.161617  
Aspartate_Aminotransferase -0.084821                   -0.072899 -0.151009  
Total_Protiens              0.783800                    0.234576  0.036443  
Albumin                     1.000000                    0.687438  0.165273  
Albumin_and_Globulin_Ratio  0.687438                    1.000000  0.171402  
Dataset                     0.165273                    0.171402  1.000000

In [144]:
liver_df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [145]:
liver_df['Disease_Status']=liver_df['Dataset'].map({1:'Yes', 2:'No'})

In [146]:
liver_df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Dataset', 'Disease_Status'],
      dtype='object')

#### Num vs Cat(Target)



*   Target = Disease_Status




In [147]:
# Age vs Target

fig = px.box(liver_df, x='Disease_Status', y='Age', title='Age vs Disease_Status')
fig.show()
fig1 = px.histogram(liver_df, x='Disease_Status', y='Age', title='Age vs Disease_Status')
fig1.show()

In [148]:
liver_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 566 entries, 0 to 582
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         566 non-null    int64  
 1   Gender                      566 non-null    object 
 2   Total_Bilirubin             566 non-null    float64
 3   Direct_Bilirubin            566 non-null    float64
 4   Alkaline_Phosphotase        566 non-null    int64  
 5   Alamine_Aminotransferase    566 non-null    int64  
 6   Aspartate_Aminotransferase  566 non-null    int64  
 7   Total_Protiens              566 non-null    float64
 8   Albumin                     566 non-null    float64
 9   Albumin_and_Globulin_Ratio  566 non-null    float64
 10  Dataset                     566 non-null    int64  
 11  Disease_Status              566 non-null    object 
dtypes: float64(5), int64(5), object(2)
memory usage: 57.5+ KB


In [149]:
num_df = liver_df.select_dtypes(include=['int64', 'float64'])
num_df.drop('Dataset', axis=1, inplace=True)
num_df

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65              0.7               0.1                   187   
1     62             10.9               5.5                   699   
2     62              7.3               4.1                   490   
3     58              1.0               0.4                   182   
4     72              3.9               2.0                   195   
..   ...              ...               ...                   ...   
578   60              0.5               0.1                   500   
579   40              0.6               0.1                    98   
580   52              0.8               0.2                   245   
581   31              1.3               0.5                   184   
582   38              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  
0        3.3                        0.90  
1        3.2                        0.74  
2        3.3                        0.89  
3        3.4                        1.00  
4        2.4                        0.40  
..       ...                         ...  
578      1.6                        0.37  
579      3.2                        1.10  
580      3.2                        1.00  
581      3.4                        1.00  
582      4.4                        1.50  

[566 rows x 9 columns]

In [150]:
for col in num_df.columns:
  fig = px.box(liver_df, x='Disease_Status', y=col, title=f'{col} vs Disease Status')
  fig1 = px.histogram(liver_df, x='Disease_Status', y=col, title=f'{col} vs Disease Status Distribution')
  fig.show()
  fig1.show()

##### Doing Hypothesis Test for require column


**Need to confirm whether these column is required or not with hypothesis test**
*   Total_Protiens
*   Albumin
*   Albumin and Globulin



In [151]:
# Total_Protiens

# class A and B scores
class_A = liver_df[liver_df['Disease_Status'] == 'Yes']['Total_Protiens']
class_B = liver_df[liver_df['Disease_Status'] == 'No']['Total_Protiens']

# Perform two-sample t-test (assume equal variances)
t_statistic, p_value = ttest_ind(class_A, class_B)

# Print the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference in Total_Protiens between Disease_Status (Yes) and Disease_Status (No).")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in Total_Protiens between Disease_Status (Yes) and Disease_Status (No).")

T-statistic: -0.8660460065089525
P-value: 0.3868331870665306
Fail to reject the null hypothesis. There is no significant difference in Total_Protiens between Disease_Status (Yes) and Disease_Status (No).


In [152]:
# Albumin

# class A and B scores
class_A = liver_df[liver_df['Disease_Status'] == 'Yes']['Albumin']
class_B = liver_df[liver_df['Disease_Status'] == 'No']['Albumin']

# Perform two-sample t-test (assume equal variances)
t_statistic, p_value = ttest_ind(class_A, class_B)

# Print the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference in Albumin between Disease_Status (Yes) and Disease_Status (No).")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in Albumin between Disease_Status (Yes) and Disease_Status (No).")

T-statistic: -3.9797464519924994
P-value: 7.799588606559988e-05
Reject the null hypothesis. There is a significant difference in Albumin between Disease_Status (Yes) and Disease_Status (No).


In [153]:
# Albumin_and_Globulin_Ratio

# class A and B scores
class_A = liver_df[liver_df['Disease_Status'] == 'Yes']['Albumin_and_Globulin_Ratio']
class_B = liver_df[liver_df['Disease_Status'] == 'No']['Albumin_and_Globulin_Ratio']

# Perform two-sample t-test (assume equal variances)
t_statistic, p_value = ttest_ind(class_A, class_B)

# Print the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference in Albumin_and_Globulin_Ratio between Disease_Status (Yes) and Disease_Status (No).")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in Albumin_and_Globulin_Ratio between Disease_Status (Yes) and Disease_Status (No).")

T-statistic: -4.131710271733096
P-value: 4.1469649677903454e-05
Reject the null hypothesis. There is a significant difference in Albumin_and_Globulin_Ratio between Disease_Status (Yes) and Disease_Status (No).


**Therefore *"Total_Protiens"* is no need for prediction**

### Droping not required column and outlier values

#### Deleting outlier values

In [154]:
# For Total_Bilirubin

liver_df[liver_df['Total_Bilirubin'] > 40]

Age Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
166   55   Male             75.0               3.6                   332   
559   26   Male             42.8              19.7                   390   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
166                        40                          66             6.2   
559                        75                         138             7.5   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
166      2.5                         0.6        1            Yes  
559      2.6                         0.5        1            Yes

In [155]:
liver_df.drop(index=liver_df[liver_df['Total_Bilirubin'] > 40].index, inplace=True)
liver_df['Total_Bilirubin']

0       0.7
1      10.9
2       7.3
3       1.0
4       3.9
       ... 
578     0.5
579     0.6
580     0.8
581     1.3
582     1.0
Name: Total_Bilirubin, Length: 564, dtype: float64

In [156]:
# For Direct_Bilirubin

liver_df.drop(index=liver_df[liver_df['Direct_Bilirubin'] > 10].index, inplace=True)
liver_df['Direct_Bilirubin'].describe()


count    547.000000
mean       1.119013
std        1.872386
min        0.100000
25%        0.200000
50%        0.300000
75%        1.100000
max       10.000000
Name: Direct_Bilirubin, dtype: float64

In [157]:
# For Alkaline_Phosphotase

liver_df[liver_df['Alkaline_Phosphotase'] > 2000]

Age Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
233   33   Male              2.0               1.4                  2110   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
233                        48                          89             6.2   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
233      3.0                         0.9        1            Yes

In [158]:
liver_df.drop(index=liver_df[liver_df['Alkaline_Phosphotase'] > 2000].index, inplace=True)
liver_df['Alkaline_Phosphotase']

0      187
1      699
2      490
3      182
4      195
      ... 
578    500
579     98
580    245
581    184
582    216
Name: Alkaline_Phosphotase, Length: 546, dtype: int64

In [159]:
fig = px.box(liver_df, x='Alkaline_Phosphotase', title='Alkaline_Phosphotase')
fig.show()

In [160]:
liver_df[(liver_df['Alamine_Aminotransferase'] > 7) & (liver_df['Alamine_Aminotransferase'] < 56)]

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
5     46    Male              1.8               0.7                   208   
6     26  Female              0.9               0.2                   154   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
3                          14                          20             6.8   
4                          27                          59             7.3   
5                          19                          14             7.6   
6                          16                          12             7.0   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
0        3.3                        0.90        1            Yes  
3        3.4                        1.00        1            Yes  
4        2.4                        0.40        1            Yes  
5        4.4                        1.30        1            Yes  
6        3.5                        1.00        1            Yes  
..       ...                         ...      ...            ...  
578      1.6                        0.37        2             No  
579      3.2                        1.10        1            Yes  
580      3.2                        1.00        1            Yes  
581      3.4                        1.00        1            Yes  
582      4.4                        1.50        2             No  

[394 rows x 12 columns]

In [161]:
liver_df[(liver_df['Aspartate_Aminotransferase'] > 10) & (liver_df['Aspartate_Aminotransferase'] < 56)]

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
3     58    Male              1.0               0.4                   182   
5     46    Male              1.8               0.7                   208   
6     26  Female              0.9               0.2                   154   
7     29  Female              0.9               0.3                   202   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
3                          14                          20             6.8   
5                          19                          14             7.6   
6                          16                          12             7.0   
7                          14                          11             6.7   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
0        3.3                        0.90        1            Yes  
3        3.4                        1.00        1            Yes  
5        4.4                        1.30        1            Yes  
6        3.5                        1.00        1            Yes  
7        3.6                        1.10        1            Yes  
..       ...                         ...      ...            ...  
578      1.6                        0.37        2             No  
579      3.2                        1.10        1            Yes  
580      3.2                        1.00        1            Yes  
581      3.4                        1.00        1            Yes  
582      4.4                        1.50        2             No  

[341 rows x 12 columns]

In [162]:
liver_df[(liver_df['Albumin'] > 3.5) & (liver_df['Albumin'] < 5.0)]

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
5     46    Male              1.8               0.7                   208   
7     29  Female              0.9               0.3                   202   
8     17    Male              0.9               0.3                   202   
13    74  Female              1.1               0.4                   214   
16    38    Male              1.8               0.8                   342   
..   ...     ...              ...               ...                   ...   
558   51    Male              4.0               2.5                   275   
566   50  Female              1.0               0.3                   191   
569   16    Male              7.7               4.1                   268   
572   32    Male             15.6               9.5                   134   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
5                          19                          14             7.6   
7                          14                          11             6.7   
8                          22                          19             7.4   
13                         22                          30             8.1   
16                        168                         441             7.6   
..                        ...                         ...             ...   
558                       382                         330             7.5   
566                        22                          31             7.8   
569                       213                         168             7.1   
572                        54                         125             5.6   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
5        4.4                         1.3        1            Yes  
7        3.6                         1.1        1            Yes  
8        4.1                         1.2        2             No  
13       4.1                         1.0        1            Yes  
16       4.4                         1.3        1            Yes  
..       ...                         ...      ...            ...  
558      4.0                         1.1        1            Yes  
566      4.0                         1.0        2             No  
569      4.0                         1.2        1            Yes  
572      4.0                         2.5        1            Yes  
582      4.4                         1.5        2             No  

[180 rows x 12 columns]

In [163]:
liver_df[(liver_df['Albumin_and_Globulin_Ratio'] > 1.0) & (liver_df['Albumin_and_Globulin_Ratio'] < 2.5)]

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
5     46    Male              1.8               0.7                   208   
7     29  Female              0.9               0.3                   202   
8     17    Male              0.9               0.3                   202   
16    38    Male              1.8               0.8                   342   
24    63    Male              0.9               0.2                   194   
..   ...     ...              ...               ...                   ...   
558   51    Male              4.0               2.5                   275   
568   20  Female             16.7               8.4                   200   
569   16    Male              7.7               4.1                   268   
579   40    Male              0.6               0.1                    98   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
5                          19                          14             7.6   
7                          14                          11             6.7   
8                          22                          19             7.4   
16                        168                         441             7.6   
24                         52                          45             6.0   
..                        ...                         ...             ...   
558                       382                         330             7.5   
568                        91                         101             6.9   
569                       213                         168             7.1   
579                        35                          31             6.0   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  Dataset Disease_Status  
5        4.4                        1.30        1            Yes  
7        3.6                        1.10        1            Yes  
8        4.1                        1.20        2             No  
16       4.4                        1.30        1            Yes  
24       3.9                        1.85        2             No  
..       ...                         ...      ...            ...  
558      4.0                        1.10        1            Yes  
568      3.5                        1.02        1            Yes  
569      4.0                        1.20        1            Yes  
579      3.2                        1.10        1            Yes  
582      4.4                        1.50        2             No  

[170 rows x 12 columns]

#### Deleting unwanted row

In [164]:
liver_df.drop(columns=['Total_Protiens'], inplace=True)

In [165]:
liver_df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Albumin', 'Albumin_and_Globulin_Ratio',
       'Dataset', 'Disease_Status'],
      dtype='object')

### Exporting cleaned data

In [166]:
liver_df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Albumin', 'Albumin_and_Globulin_Ratio',
       'Dataset', 'Disease_Status'],
      dtype='object')

In [167]:
liver_df.drop('Dataset', axis=1, inplace=True)

In [168]:
liver_df.to_csv('liver_disease_cleaned.csv', index=False)

## ML - Model selection and Traning

### Importing necessary packages

In [169]:
# Data preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN

In [170]:
# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

# Evaluation metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import confusion_matrix, classification_report

In [171]:
# Importing lib for Pipeline

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OrdinalEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer

### Train, Test Split and Scaling, Encoding

In [172]:
# liver_df['Disease_Status_binary'] = liver_df['Disease_Status'].map({'Yes': 1, 'No': 0})

In [173]:
X = liver_df.drop(['Disease_Status'], axis=1)
Y = liver_df['Disease_Status']

In [174]:
# Seperating Numerical and Categorical Features
# For 1st we seperating Numerical into 2 types one is Continues and Discreat

num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include=['object', 'category']).columns

In [175]:
num_cols

Index(['Age', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkaline_Phosphotase',
       'Alamine_Aminotransferase', 'Aspartate_Aminotransferase', 'Albumin',
       'Albumin_and_Globulin_Ratio'],
      dtype='object')

##### Encoding-Pipeline

In [176]:
# Creating transformer for Numerical con columns

num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

num_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [177]:
# Finding Cross Tab to get order for Cat column - Target Encoding

crosstab = pd.crosstab(liver_df['Gender'], liver_df['Disease_Status'])
crosstab['Status_ratio'] = crosstab['Yes'] / (crosstab['Yes'] + crosstab['No'])
sorted_index = crosstab.sort_values(by='Status_ratio', ascending=False).index
sorted_index

Index(['Male', 'Female'], dtype='object', name='Gender')

In [178]:
# Creating transformer for cat odinal column

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(categories=[sorted_index]))
])

cat_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OrdinalEncoder(categories=[Index(['Male', 'Female'], dtype='object', name='Gender')]))])

In [179]:
# Combining the all transformer as a full loaded pipeline with column transformer

preprocess = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ])

preprocess

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['Age', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkaline_Phosphotase',
       'Alamine_Aminotransferase', 'Aspartate_Aminotransferase', 'Albumin',
       'Albumin_and_Globulin_Ratio'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[Index(['Male', 'Female'], dtype='object', name='Gender')]))]),
                                 Index(['Gender'], dtype='object'))])

#### ML - Pipeline

##### Data Balancing

In [180]:
from imblearn.pipeline import Pipeline as IMBPipeline

In [181]:
from imblearn.over_sampling import SMOTE

In [182]:
liver_df['Disease_Status'].value_counts()

Disease_Status
Yes    384
No     162
Name: count, dtype: int64

* We can choose ADASYN

In [183]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

##### LogReg

In [184]:
# Creating pipeline for LogReg

logreg_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('classifier', LogisticRegression(C=10.0,class_weight="balanced",penalty='l2', max_iter=300,multi_class='deprecated',intercept_scaling=1))
])

logreg_pipeline.fit(X_train,Y_train)

Y_train_pred=logreg_pipeline.predict(X_train)
Y_test_pred=logreg_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)


Confusion Matrix Train
----------------------------------------------------------------------------------------------------
[[118  13]
 [ 82 223]]
Confusion Matrix Test
----------------------------------------------------------------------------------------------------
[[19 12]
 [20 59]]
****************************************************************************************************
Classification Report Train
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

          No       0.59      0.90      0.71       131
         Yes       0.94      0.73      0.82       305

    accuracy                           0.78       436
   macro avg       0.77      0.82      0.77       436
weighted avg       0.84      0.78      0.79       436

Classification Report Test
----------------------------------------------------------------------------------------------------
              precision   

##### SVC

In [185]:
svc_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('classifier', SVC(class_weight="balanced", kernel='poly',  C=1.0,))
])

logreg_pipeline.fit(X_train,Y_train)

Y_train_pred=logreg_pipeline.predict(X_train)
Y_test_pred=logreg_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)


Confusion Matrix Train
----------------------------------------------------------------------------------------------------
[[118  13]
 [ 82 223]]
Confusion Matrix Test
----------------------------------------------------------------------------------------------------
[[19 12]
 [20 59]]
****************************************************************************************************
Classification Report Train
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

          No       0.59      0.90      0.71       131
         Yes       0.94      0.73      0.82       305

    accuracy                           0.78       436
   macro avg       0.77      0.82      0.77       436
weighted avg       0.84      0.78      0.79       436

Classification Report Test
----------------------------------------------------------------------------------------------------
              precision   

##### DecisionTreeClassifier

In [186]:
# Creating pipeline for DecisionTreeClassifier

dt_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('classifier', DecisionTreeClassifier(class_weight={'No':4,'Yes':9},criterion='gini',splitter='best',max_depth=None,min_samples_split=10,min_samples_leaf=35,random_state=42))
])

dt_pipeline.fit(X_train,Y_train)

Y_train_pred=dt_pipeline.predict(X_train)
Y_test_pred=dt_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)

Confusion Matrix Train
----------------------------------------------------------------------------------------------------
[[ 70  61]
 [ 39 266]]
Confusion Matrix Test
----------------------------------------------------------------------------------------------------
[[18 13]
 [11 68]]
****************************************************************************************************
Classification Report Train
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

          No       0.64      0.53      0.58       131
         Yes       0.81      0.87      0.84       305

    accuracy                           0.77       436
   macro avg       0.73      0.70      0.71       436
weighted avg       0.76      0.77      0.76       436

Classification Report Test
----------------------------------------------------------------------------------------------------
              precision   

###### Exporting Selected Model

In [187]:
import pickle

In [188]:
pickle.dump(dt_pipeline, open('dt_pipeline.pkl', 'wb'))

In [191]:
from sklearn.decomposition import PCA

In [192]:
# Creating pipeline for DecisionTreeClassifier

dt_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('PCA',PCA(n_components=4)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('classifier', DecisionTreeClassifier(class_weight={'No':4,'Yes':9},criterion='gini',splitter='best',max_depth=150,min_samples_split=10,min_samples_leaf=15))
])

dt_pipeline.fit(X_train,Y_train)

Y_train_pred=dt_pipeline.predict(X_train)
Y_test_pred=dt_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)

Confusion Matrix Train
----------------------------------------------------------------------------------------------------
[[ 71  60]
 [ 22 283]]
Confusion Matrix Test
----------------------------------------------------------------------------------------------------
[[ 9 22]
 [11 68]]
****************************************************************************************************
Classification Report Train
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

          No       0.76      0.54      0.63       131
         Yes       0.83      0.93      0.87       305

    accuracy                           0.81       436
   macro avg       0.79      0.73      0.75       436
weighted avg       0.81      0.81      0.80       436

Classification Report Test
----------------------------------------------------------------------------------------------------
              precision   

##### Random Forest

In [193]:
# Creating pipeline for Random Forest

rf_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',SMOTE(random_state=42)),
    ('Poly',PolynomialFeatures(degree=4)),
    ('classifier', RandomForestClassifier(class_weight={'No':5,'Yes':8},
                  max_features='sqrt',
                  criterion='log_loss',
                  n_estimators=500,
                  max_depth=200,
                  max_samples=600,
                  min_samples_split=45,
                  min_samples_leaf=70,
                  max_leaf_nodes=100))
])

rf_pipeline.fit(X_train,Y_train)

Y_train_pred=rf_pipeline.predict(X_train)
Y_test_pred=rf_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)

Confusion Matrix Train
----------------------------------------------------------------------------------------------------
[[ 66  65]
 [ 47 258]]
Confusion Matrix Test
----------------------------------------------------------------------------------------------------
[[15 16]
 [11 68]]
****************************************************************************************************
Classification Report Train
----------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

          No       0.58      0.50      0.54       131
         Yes       0.80      0.85      0.82       305

    accuracy                           0.74       436
   macro avg       0.69      0.67      0.68       436
weighted avg       0.73      0.74      0.74       436

Classification Report Test
----------------------------------------------------------------------------------------------------
              precision   

In [195]:
# # PCA

# pca = PCA(n_components=5)
# pca.fit(X_train)
# X_train_pca = pca.transform(X_train)
# X_test_pca = pca.transform(X_test)

##### XG-Boost

In [ ]:
XG_pipeline = IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('classifier', XGBClassifier(objective='binary:logistic'))
])

XG_pipeline.fit(X_train,Y_train)

Y_train_pred=XG_pipeline.predict(X_train)
Y_test_pred=XG_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)

##### KNeighborsClassifier

In [ ]:
KNeighborsClassifier_pipeline=IMBPipeline(steps=[
    ('preprocess', preprocess),
    ('Sampling',ADASYN(random_state=42)),
    ('Poly',PolynomialFeatures(degree=3)),
    ('knn',KNeighborsClassifier(n_neighbors=5))
])

KNeighborsClassifier_pipeline.fit(X_train,Y_train)

Y_train_pred=KNeighborsClassifier_pipeline.predict(X_train)
Y_test_pred=KNeighborsClassifier_pipeline.predict(X_test)

print('Confusion Matrix Train')
print('--'*50)
print(confusion_matrix(Y_train,Y_train_pred))
print('Confusion Matrix Test')
print('--'*50)
print(confusion_matrix(Y_test,Y_test_pred))
print('**'*50)
print('Classification Report Train')
print('--'*50)
print(classification_report(Y_train,Y_train_pred))
print('Classification Report Test')
print('--'*50)
print(classification_report(Y_test,Y_test_pred))
print('--'*50)