<a href="https://colab.research.google.com/github/Infant-Joshva/Data-Science-learning-path/blob/main/Practice_NumPy_%26_SciPy_Git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Practice Sheet

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
A=np.array([1,2,3,4,5])
print(A)
print(type(A))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
B=np.array([[1,2,3],
            [4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [ ]:
B.shape

(2, 3)

In [ ]:
B.dtype

dtype('int64')

In [ ]:
C=np.zeros((2,3),dtype=int)
C

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
C.dtype

dtype('int64')

In [ ]:
D=np.ones((2,3),dtype=int)
D

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
C+D

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
B+D

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
B*D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
L1=np.array([[10,20,30],[40,50,60],[70,80,90]])
L2=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(L1+L2)
print(L1*L2)
print(L1/L2)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [ ]:
np.dot(L1,L2)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [ ]:
L1=np.array([[1,2],[4,5]])
L2=np.array([[10,20],[30,40]])

print("Multiplication of L1 and L2 is:",L1,L2)
print("Dot product of L1 and L2",np.dot(L1,L2))

Multiplication of L1 and L2 is: [[1 2]
 [4 5]] [[10 20]
 [30 40]]
Dot product of L1 and L2 [[ 70 100]
 [190 280]]


In [ ]:
Age=[25,30,35,80,30,18,20,30,25,21]

Age=np.array(Age)
print(Age)
print(type(Age))

[25 30 35 80 30 18 20 30 25 21]
<class 'numpy.ndarray'>


In [ ]:
Age.mean()

np.float64(31.4)

In [ ]:
Age.max()

np.int64(80)

In [ ]:
Age.min()

np.int64(18)

In [ ]:
np.median(Age)

np.float64(27.5)

In [ ]:
np.std(Age)

np.float64(16.97174121886143)

In [ ]:
np.var(Age)

np.float64(288.04)

#SciPy

In [ ]:
from scipy import stats

In [ ]:
stats.mode(Age, keepdims=False)

ModeResult(mode=np.int64(30), count=np.int64(3))

In [ ]:
Class1=[20,30,40,40,60]
Class2=[40,60,60,60,70]

classes_Age=np.array([Class1,Class2])
print(classes_Age)

[[20 30 40 40 60]
 [40 60 60 60 70]]


In [ ]:
stats.mode(classes_Age, keepdims=True,axis=1)

ModeResult(mode=array([[40],
       [60]]), count=array([[2],
       [3]]))

In [ ]:
Salary=[20000,30000,4000,20000,15000,30000,25000,80000,22000]

# 5 Number summary

print('Min :',np.min(Salary))
print('Q1 :',np.percentile(Salary,25))
print('Q2 :',np.percentile(Salary,50))
print('Q3 :',np.percentile(Salary,75))
print('Max :',np.max(Salary))
print('IQR :',np.percentile(Salary,75)-np.percentile(Salary,25))

Min : 4000
Q1 : 20000.0
Q2 : 22000.0
Q3 : 30000.0
Max : 80000
IQR : 10000.0


In [ ]:
# Filter outlier

Q1=np.percentile(Salary,25)
Q3=np.percentile(Salary,75)

IQR=Q3-Q1

print(Q1)
print(Q3)
print(IQR)

20000.0
30000.0
10000.0


In [ ]:
upper_bound=Q3+(1.5*IQR)
lower_bound=Q1-(1.5*IQR)

print(upper_bound)
print(lower_bound)

45000.0
5000.0


In [ ]:
# Filter the Outlier

New_Data=[]

for i in Salary:
  if i>=lower_bound and i<=upper_bound:
    New_Data.append(i)

print(New_Data)

[20000, 30000, 20000, 15000, 30000, 25000, 22000]


In [ ]:
import pandas as pd
SaL_Detail={'Name':['A','B','C','D','E','F','G','H','I'],'Salary':[20000,30000,4000,20000,15000,30000,25000,80000,22000]}

df=pd.DataFrame(SaL_Detail)
df

Name  Salary
0    A   20000
1    B   30000
2    C    4000
3    D   20000
4    E   15000
5    F   30000
6    G   25000
7    H   80000
8    I   22000

In [ ]:
df[(df['Salary']<upper_bound)&(df['Salary']>lower_bound)]

Name  Salary
0    A   20000
1    B   30000
3    D   20000
4    E   15000
5    F   30000
6    G   25000
8    I   22000

####Hypothesis-> 1 Sample T-Test(Using Numpy(Manual Calc)

In [ ]:
## One sample T test

# Null Hypo == There is 5 Cm Change in Height while consume complan

# Alternate Hypo == There is less than 5 Cm Change in Height while consume complan


# Significance Level == 0.1

# Alpha == 0.1

Height_gain=[3,4,5,5,7,3,3.6,4.8,5,6]

# T- Statstics

Sample_mean=np.mean(Height_gain)
Pop_mean=5
Sample_std=np.std(Height_gain)
Num_Sample=len(Height_gain)

print(Sample_mean)
print(Pop_mean)
print(Sample_std)
print(Num_Sample)

4.64
5
1.2126005112979295
10


In [ ]:
T=(Sample_mean-Pop_mean)/(Sample_std/np.sqrt(Num_Sample))
T

np.float64(-0.938825233086937)

In [ ]:
T_stat=(Sample_mean-Pop_mean)/(Sample_std/np.sqrt(Num_Sample))
T_stat

np.float64(-0.938825233086937)

In [ ]:
# Critical T

DF=Num_Sample-1
Alpha=0.1
T_critc=-1.383


if T_stat>T_critc:
  print(' Accept Alternate Hypothesis: There is less than 5 Cm Change in Height while consume complan')
else:
  print(' Accept Null Hypothesis: There is 5 Cm Change in Height while consume complan')



 Accept Alternate Hypothesis: There is less than 5 Cm Change in Height while consume complan


####Hypothesis->

#### 1 Sample T-Test(Using Numpy & SciPy)

In [ ]:
# Null Hypo: 100 Grm in DairyMilk Chocolate
# Alternate Hypo: <100 Grm in DairyMilk Chocolate

Dairy_Mily=np.array([98.5,101.5,102.5,100.0,99.0,99.5,97.5,98.0,101.0,100.0,95.5])

Sample_mean=np.mean(Dairy_Mily)
Pop_mean=100
Sample_std=np.std(Dairy_Mily)
Num_Sample=len(Dairy_Mily)

print(Sample_mean)
print(Pop_mean)
print(Sample_std)
print(Num_Sample)



99.36363636363636
100
1.8840347069147916
11


In [ ]:
T_stats,P_value=stats.ttest_1samp(Dairy_Mily,popmean=100)
print(T_stats)
print(P_value)

-1.0681111678200446
0.31057617380056224


In [ ]:
Alpha=0.05

if P_value<Alpha:
  print('Reject Null Hypo: 100 Grm in DairyMilk Chocolate')
else:
  print('Accept Null Hypo: 100 Grm in DairyMilk Chocolate')


Accept Null Hypo: 100 Grm in DairyMilk Chocolate


#### 2 Sample Test(Using Numpy & SciPy)

🧪 Scenario: Comparing Exam Scores Between Two Teaching Methods
Background:
A school wants to evaluate whether a new teaching method leads to better student performance compared to the traditional method. Two groups of students are taught the same subject over the same time period, but with different teaching styles.

Group A: 30 students taught using the traditional method

Group B: 30 students taught using the new method

At the end of the course, both groups take the same standardized test.


---


🔍 Hypothesis Test: Two-Sample t-Test
Objective:
To determine whether the mean test scores between the two groups are significantly different.

Assumptions:
The two samples are independent.

The test scores are approximately normally distributed.

The variances are equal (or not—this affects which version of the test is used).



---

📊 Hypotheses:
Null Hypothesis (H₀):
There is no difference in mean scores between the two groups.


Alternative Hypothesis (H₁):
There is a difference in mean scores.

(This is a two-tailed test. If you expect one method to be better, use a one-tailed test.)



📊 Sample Dataset (Scores out of 100):


---


Group A (Traditional Method)
[72, 68, 75, 70, 74, 69, 71, 67, 73, 70]


---


Group B (New Method)
[78, 82, 80, 85, 79, 81, 83, 84, 80, 77]

In [3]:
# 2 Sample T-Test
import numpy as np
from scipy import stats

# Sample data for two groups
group1 = np.array( [72, 68, 75, 70, 74, 69, 71, 67, 73, 70])  # Sample 1
group2 = np.array([78, 82, 80, 85, 79, 81, 83, 84, 80, 77])  # Sample 2

t_statistic, p_value = stats.ttest_ind(group1, group2, equal_var=False)

print("T-statistic:", t_statistic)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject the null hypothesis. There is a significant difference in mean scores between the two groups.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in mean scores between the two groups.")

T-statistic: -8.596023825918794
P-value: 8.678241057643692e-08
Reject the null hypothesis. There is a significant difference in mean scores between the two groups.


#### 3.Paired Test(Using Numpy & SciPy)

In [4]:
import numpy as np
from scipy.stats import ttest_rel

# Sample Data: Test scores of 8 students (Before and After training)
before = np.array([60, 65, 70, 58, 80, 76, 72, 68])
after  = np.array([65, 70, 75, 60, 85, 80, 74, 70])

# Perform Paired T-Test
t_stat, p_value = ttest_rel(before, after)

# Print the result
print("T-statistic:", t_stat)
print("P-value:", p_value)

# Decision
if p_value < 0.05:
    print("Result: Reject Null → Training had a significant effect")
else:
    print("Result: Fail to Reject Null → No significant effect from training")


T-statistic: -7.127864449672373
P-value: 0.00018898527232857066
Result: Reject Null → Training had a significant effect


#### 4.Z-Test (Large Sample)

In [5]:
# Sample from a class
sample = np.array([78, 76, 74, 79, 77, 80, 75, 73, 76, 78])

# Population mean = 75
# Use Z-test to check if sample mean ≠ 75

sample_mean=np.mean(sample)
pop_mean=75
sample_std=np.std(sample)
num_sample=len(sample)

print(sample_mean)
print(pop_mean)
print(sample_std)
print(num_sample)

76.6
75
2.1071307505705477
10


In [6]:
T_stats,P_value=stats.ttest_1samp(sample,popmean=75)
print(T_stats)
print(P_value)

2.27797918980599
0.04872323324522449


In [7]:
Alpha=0.05

if P_value<Alpha:
  print('Reject Null Hypo: Sample mean ≠ 75')
else:
  print('Accept Null Hypo: Sample mean = 75')

Reject Null Hypo: Sample mean ≠ 75


#### 5.Chi-Square Test

|        | Coffee | Tea |
| ------ | ------ | --- |
| Male   | 10     | 5   |
| Female | 4      | 11  |


In [10]:
import numpy as np
from scipy.stats import chi2_contingency

# Create contingency table as NumPy array
data = np.array([[10, 5],
                 [4, 11]])

# Perform test
chi2, p, dof, expected = chi2_contingency(data)


# Print results
print("Chi-Square Statistic:", chi2)
print("P-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

if p < 0.05:
    print("Reject the null hypothesis. There is a significant association between gender and preference.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between gender and preference.")

Chi-Square Statistic: 3.3482142857142856
P-value: 0.06727796053834906
Degrees of Freedom: 1
Expected Frequencies:
 [[7. 8.]
 [7. 8.]]
Fail to reject the null hypothesis. There is no significant association between gender and preference.


🧮 What Does ANOVA Do?
It compares:

Variation between groups (Are group means far apart?)
Variation within groups (How spread out scores are inside each group)
If between-group variation is large compared to within-group variation, then we conclude that at least one group is different.

In [13]:
from scipy.stats import f_oneway

# Test scores from 3 different classes
class_a = [85, 90, 88, 75, 95]
class_b = [70, 65, 60, 72, 68]
class_c = [80, 78, 82, 85, 88]

# Perform one-way ANOVA
f_stat, p_val = f_oneway(class_a, class_b, class_c)

print(f"F-statistic: {f_stat:.4f}")
print(f"p-value: {p_val:.4f}")

# Interpret result
alpha = 0.05
if p_val < alpha:
    print("Reject the null hypothesis: At least one group is significantly different.")
else:
    print("Fail to reject the null hypothesis: No significant difference.")

F-statistic: 17.2803
p-value: 0.0003
Reject the null hypothesis: At least one group is significantly different.
