<a href="https://colab.research.google.com/github/Infant-Joshva/Data-Science-learning-path/blob/main/DS-Practice-Notebooks/DS04-DL-NLP/TensorFlow_Framework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [6]:
print(tf.config.list_physical_devices('GPU'))
print(tf.config.list_logical_devices('CPU'))
print(tf.config.list_logical_devices('TPU'))

[]
[LogicalDevice(name='/device:CPU:0', device_type='CPU')]
[]


In [7]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
tf.random.normal([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.08809496,  0.391457  , -0.61286825],
       [ 0.96670157,  0.24832828, -0.33538926]], dtype=float32)>

In [9]:
tf.ones([1,1])

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [10]:
!pip install keras

## Regression

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing

In [15]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [16]:
data=fetch_california_housing()
x=data.data
y=data.target

In [17]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [18]:
df=pd.DataFrame(data.data, columns=data.feature_names)
df['y']=data.target
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude      y  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16512, 8), (4128, 8), (16512,), (4128,))

In [21]:
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train) # Fit and transform
X_test_scaled=scalar.transform(X_test) # Only transform

In [22]:
# convert to tensors
X_train_tensor=tf.convert_to_tensor(X_train_scaled, dtype=tf.float32)
X_test_tensor=tf.convert_to_tensor(X_test_scaled, dtype=tf.float32)
y_train_tensor=tf.convert_to_tensor(y_train, dtype=tf.float32)
y_test_tensor=tf.convert_to_tensor(y_test, dtype=tf.float32)

In [24]:
# Model Define

model=Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],))) #Input layers
model.add(Dense(32, activation='relu')) #Hidden Layers
model.add(Dense(1)) #Output Layers
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
# Compling
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [27]:
# Fit
# Mini batch
model.fit(X_train,y_train, epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 7058.2031 - mae: 27.9744 - val_loss: 1.9231 - val_mae: 1.1103
Epoch 2/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.8731 - mae: 1.0317 - val_loss: 1.5021 - val_mae: 0.9258
Epoch 3/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.4794 - mae: 0.9490 - val_loss: 1.1793 - val_mae: 0.8743
Epoch 4/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.5845 - mae: 1.0820 - val_loss: 1.0781 - val_mae: 0.7766
Epoch 5/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.0750 - mae: 0.8086 - val_loss: 0.9902 - val_mae: 0.7416
Epoch 6/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.1054 - mae: 0.8053 - val_loss: 1.4584 - val_mae: 0.9916
Epoch 7/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.2716 - mae: 0.8295 - val_loss: 0.8167 - val_mae: 0.6966
Epoch 8/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 14.1167 - mae: 2.0287 - val_loss: 0.7965 - val_mae: 0.6626
Epoch 9/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,069 (31.52 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,380 (21.02 KB)

In [30]:
model.save('TF_reg.h5')

In [31]:
model.save('TF_reg.keras')

In [ ]:
# Fit
# Mini batch
model.fit(X_train,y_train, epochs=100, validation_data=(X_test,y_test))

### Stochastic Gradient Descent (SGD)



```
# Updating bias once per data
```



In [32]:
model.fit(X_train,y_train, epochs=3, validation_data=(X_test,y_test), batch_size=1)

Epoch 1/3
16512/16512 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - loss: 0.8535 - mae: 0.6943 - val_loss: 0.6547 - val_mae: 0.6131
Epoch 2/3
16512/16512 ━━━━━━━━━━━━━━━━━━━━ 42s 3ms/step - loss: 0.7489 - mae: 0.6477 - val_loss: 0.6833 - val_mae: 0.6755
Epoch 3/3
16512/16512 ━━━━━━━━━━━━━━━━━━━━ 37s 2ms/step - loss: 0.6531 - mae: 0.6030 - val_loss: 0.5813 - val_mae: 0.5594


### Batch Gradient Descent (SGD)



```
# Updating once per whole data
```



In [34]:
X_train.shape[0]

16512

In [36]:
model.fit(X_train,y_train, epochs=3, validation_data=(X_test,y_test), batch_size=X_train.shape[0]) #Batch GD

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - loss: 0.5675 - mae: 0.5556 - val_loss: 0.5889 - val_mae: 0.5624
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - loss: 0.5751 - mae: 0.5587 - val_loss: 0.5947 - val_mae: 0.5648
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step - loss: 0.5809 - mae: 0.5612 - val_loss: 0.5984 - val_mae: 0.5664


### Mini Batch Gradient Descent (SGD)



```
# Updating bias per mini batch
```



In [33]:
X_train.shape[0]/64

258.0

In [37]:
model.fit(X_train,y_train, epochs=20, validation_data=(X_test,y_test), batch_size=64) #Batch GD

Epoch 1/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5399 - mae: 0.5492 - val_loss: 0.5234 - val_mae: 0.5469
Epoch 2/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4959 - mae: 0.5316 - val_loss: 0.5203 - val_mae: 0.5399
Epoch 3/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4943 - mae: 0.5266 - val_loss: 0.5250 - val_mae: 0.5348
Epoch 4/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5092 - mae: 0.5315 - val_loss: 0.5081 - val_mae: 0.5312
Epoch 5/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4870 - mae: 0.5251 - val_loss: 0.5099 - val_mae: 0.5235
Epoch 6/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4839 - mae: 0.5194 - val_loss: 0.5094 - val_mae: 0.5303
Epoch 7/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4954 - mae: 0.5221 - val_loss: 0.5171 - val_mae: 0.5235
Epoch 8/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4974 - mae: 0.5230 - val_loss: 0.5179 - val_mae: 0.5448
Epoch 9/20
258/258 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - lo